Repository umm-as/gartic-umm, pull requests merged in 2023-06, with the labels that each got.

#38 fix issues at #37
  GarticUmm.sln
  GarticUmm/Form2.Designer.cs
  GarticUmm/Form2.cs
  GarticUmm/Form2.resx
  GarticUmm/SharedObject.cs
  GarticUmm/SocketServer.cs
  GarticUmm/UmmQueue.cs
Labels: fix

#39 implenemt present stage
  GarticUmm/Form2.cs
  GarticUmm/SharedObject.cs
  GarticUmm/SocketClient.cs
  GarticUmm/SocketServer.cs
  GarticUmm/UmmQueue.cs
Labels: implement

#42 fix send image error
  GarticUmm.sln
  GarticUmm/Form2.cs
  GarticUmm/SocketServer.cs
Labels: fix

#43 implement image rotation and remove test code
  GarticUmm/Form2.Designer.cs
  GarticUmm/Form2.cs
  GarticUmm/Form2.resx
  GarticUmm/SharedObject.cs
  GarticUmm/SocketClient.cs
  GarticUmm/SocketServer.cs
  GarticUmm/UmmQueue.cs
  GarticUmm/UmmTimer.cs
Labels: implement

#46 게임 종료시 게임 결과 출력(개발 단계)
  GarticUmm/Form2.cs
  GarticUmm/Form4.Designer.cs
  GarticUmm/Form4.cs
  GarticUmm/Form4.resx
  GarticUmm/GarticUmm.csproj
  GarticUmm/SharedObject.cs
  GarticUmm/SocketClient.cs
  GarticUmm/SocketServer.cs
Labels: invalid

#47 게임 종료 시 게임 결과 출력(오류 존재)
  GarticUmm/Form2.cs
  GarticUmm/Form4.Designer.cs
  GarticUmm/Form4.cs
  GarticUmm/SharedObject.cs
  GarticUmm/SocketClient.cs
  GarticUmm/SocketServer.cs
  GarticUmm/UmmTimer.cs
Labels: help wanted

#48 implement result controller (solve #47)
  GarticUmm/Form2.cs
  GarticUmm/Form4.Designer.cs
  GarticUmm/Form4.cs
  GarticUmm/SharedObject.cs
  GarticUmm/SocketClient.cs
  GarticUmm/SocketServer.cs
  GarticUmm/UmmTimer.cs
  README.md
Labels: implement, fix

#50 implement specific ipaddress
  GarticUmm/Form1.cs
  GarticUmm/Form2.cs
  GarticUmm/Form5.Designer.cs
  GarticUmm/Form5.cs
  GarticUmm/Form5.resx
  GarticUmm/GarticUmm.csproj
  GarticUmm/SocketClient.cs
  GarticUmm/SocketServer.cs
Labels: implement

#51 ip 출력 형식 변경
  GarticUmm/Form2.cs
Labels: fix

#54 제시어 미입력 시 게임 진행 불가
  GarticUmm/Form2.Designer.cs
  GarticUmm/Form2.cs
  GarticUmm/Form3.Designer.cs
  GarticUmm/Form3.cs
  GarticUmm/Form5.Designer.cs
  GarticUmm/Form5.cs
  GarticUmm/SocketServer.cs
Labels: fix
